apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: int
  namespace: openshift-ingress-operator
spec:
  domain: int.sno-2.sandbox2917.opentlc.com # MODIFY
  namespaceSelector:
    matchLabels:
      router: "int"
  replicas: 1
  routeSelector:
    matchLabels:
      router: "int"
