apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: pre
  namespace: openshift-ingress-operator
spec:
  domain: pre.sno-2.sandbox2917.opentlc.com # MODIFY
  namespaceSelector:
    matchLabels:
      router: "pre"
  replicas: 1
  routeSelector:
    matchLabels:
      router: "pre"
