kind: Secret
apiVersion: v1
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: >-
    YWRtaW46JDJ5JDA1JHc2YVhFb1dHWUYzSk81Sk5rT3Fra3VuRXouRkx5ZlMvbnRTb3ozdGhFb0h3dFNmUTRSdGxXCnBldGVyOiQyeSQwNSRCLmxBajJWaEExdmFsUkZZUGp4a0R1WnZDOC5qWDlvSU1NOXlMOW5HN3Q3UG13dlBPQUJkUwprYXJsYTokMnkkMDUkN2NKS0w4ZzY2MEVEU1AzVWVxNGF4LnQ0WWxUc0JxalBxS3F0czR6MGk4Wi5nMnJBQnc0RlcKYW5uYTokMnkkMDUkNnNnLm01bDBCNlUweTJtbXl6a3EudVBOZUlZa2ZZVVg1RFZCM0lSYzNwOU1WOC96MFFSMFMK
type: Opaque
