---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
  - oauth/oauth.yaml

resources:
  - htpasswd/htpass-secret.yaml
  - htpasswd/clusteradmin-clusterrolebinding.yaml
  - keycloak/keycloak-ca.yaml
  - keycloak/keycloak-secret.yaml
